{
 "title": "PostgreSQL Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Server", "query": "collectd.*" },
   { "name": "Databases", "query": "collectd.$Server.postgres*" }
  ]
 },
 "panels": [
  { "title": "Summarize", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(collectd.$Server.$Databases.pg_numbackends)"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(collectd.$Server.$Databases.pg_db_size)"
    }
   ]
  },
  {
   "title": "Percent of Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "asPercent(sumSeries(collectd.$Server.$Databases.pg_db_size),sumSeries(#A,#B))",
     "targetFull": "asPercent(sumSeries(collectd.$Server.$Databases.pg_db_size),sumSeries(sumSeries(collectd.$Server.df-mapper_databases_vg-databases.df_*),sumSeries(collectd.$Server.df-sd*.df_complex-{used,reserved,free})))"
    }
   ]
  },
  {
   "title": "Dead Tuples",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "asPercent(sumSeries(collectd.$Server.$Databases.pg_n_tup_g-dead),sumSeries(collectd.$Server.$Databases.pg_n_tup_g-{live,dead}))"
    }
   ]
  },
  {
   "title": "Tables Hit Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "asPercent(sumSeries(collectd.$Server.$Databases.pg_blks-{heap,toast}_hit),sumSeries(collectd.$Server.$Databases.pg_blks-{heap,toast}_{hit,read}))"
    }
   ]
  },
  {
   "title": "Indexes Hit Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "asPercent(sumSeries(collectd.$Server.$Databases.pg_blks-{idx,tidx}_hit),sumSeries(collectd.$Server.$Databases.pg_blks-{idx,tidx}_{hit,read}))"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  },
  {
   "title": "Commits and Rollbacks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$Server.$Databases.pg_xact-commit, 'Commits')"
    },
    {
     "target": "alias(collectd.$Server.$Databases.pg_xact-rollback, 'Rollbacks')"
    }
   ]
  },
  {
   "title": "Inserts, Updates and Deletes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$Server.$Databases.pg_n_tup_c-ins, 'Insert')"
    },
    {
     "target": "alias(collectd.$Server.$Databases.pg_n_tup_c-upd, 'Update')"
    },
    {
     "target": "alias(collectd.$Server.$Databases.pg_n_tup_c-hot_upd, 'Hot Update')"
    },
    {
     "target": "alias(collectd.$Server.$Databases.pg_n_tup_c-del, 'Delete')"
    }
   ]
  },
  {
   "title": "Scannings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$Server.$Databases.pg_scan-idx, 'Index')"
    },
    {
     "target": "alias(collectd.$Server.$Databases.pg_scan-seq, 'Sequencial')"
    }
   ]
  },
  {
   "title": "Garbage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$Server.$Databases.pg_n_tup_g-live, 'Lives')"
    },
    {
     "target": "alias(collectd.$Server.$Databases.pg_n_tup_g-dead, 'Deads')"
    }
   ]
  },
  {
   "title": "Hits and Reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$Server.$Databases.pg_blks-heap_hit, 'Heap Hit')"
    },
    {
     "target": "alias(collectd.$Server.$Databases.pg_blks-heap_read, 'Heap Read')"
    },
    {
     "target": "alias(collectd.$Server.$Databases.pg_blks-idx_hit, 'Index Hit')"
    },
    {
     "target": "alias(collectd.$Server.$Databases.pg_blks-idx_read, 'Index Read')"
    },
    {
     "target": "alias(collectd.$Server.$Databases.pg_blks-tidx_hit, 'Toast Index Hit')"
    },
    {
     "target": "alias(collectd.$Server.$Databases.pg_blks-tidx_read, 'Toast Index Read')"
    },
    {
     "target": "alias(collectd.$Server.$Databases.pg_blks-toast_hit, 'Toast Hit')"
    },
    {
     "target": "alias(collectd.$Server.$Databases.pg_blks-toast_read, 'Toast Read')"
    }
   ]
  }
 ]
}