{
 "description": "Collectd/Graphite Server metrics dashboard (Load,CPU, Memory, Temp etc) - DAPP/FGV",
 "tags": [ "academica" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Server", "query": "${VAR_SERVER}" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "description": "CPU Percent Usage",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "sum(exclude(collectd.$Server.aggregation-cpu-average.cpu-*, 'idle'))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "description": "Memory Percent Usage",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(asPercent(sumSeries(collectd.$Server.memory.memory-used), sumSeries(collectd.$Server.memory.memory-*)), \"Memory Used\")"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "description": "Disk Percent Usage",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(asPercent(sumSeries(collectd.$Server.df-*.df_complex-used), sumSeries(collectd.$Server.df-*.df_complex-*)), \"Disk Used\")"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "collectd.$Server.aggregation-cpu-num.cpu-system"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 6 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(sumSeries(collectd.$Server.memory.memory-*),\"Total Memory\")"
    },
    {}
   ]
  },
  {
   "title": "Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(collectd.$Server.df-mapper_centos*-{root,home}.df_complex-{used,reserved,free})"
    }
   ]
  },
  { "title": "General Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Available Entropy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "collectd.$Server.entropy.entropy"
    }
   ]
  },
  {
   "title": "5min Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "collectd.$Server.load.load.midterm"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "target": "collectd.$Server.uptime.uptime" }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "collectd.$Server.users.users" }
   ]
  },
  { "title": "CPU / Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.cpu-interrupt), 3)"
    },
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.cpu-nice), 3)"
    },
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.cpu-softirq), 3)"
    },
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.cpu-steal), 3)"
    },
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.cpu-system), 3)"
    },
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.cpu-user), 3)"
    },
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.cpu-wait), 3)"
    },
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.cpu-idle), 3)"
    },
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.percent-interrupt), 3)"
    },
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.percent-nice), 3)"
    },
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.percent-softirq), 3)"
    },
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.percent-steal), 3)"
    },
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.percent-system), 3)"
    },
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.percent-user), 3)"
    },
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.percent-wait), 3)"
    },
    {
     "target": "aliasByNode(averageSeries(collectd.$Server.cpu-*.percent-idle), 3)"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(collectd.$Server.processes.ps_state-running, 2), 'Running processes')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C, #D, #E, #F), \"Total\")"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Free diskspace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.$Server.df-*.percent_bytes-free, 2)"
    }
   ]
  },
  {
   "title": "Used diskspace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.$Server.df-*.percent_bytes-used, 2)"
    }
   ]
  },
  {
   "title": "Disk throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.$Server.*.disk_octets.*, 2, 3, 4)"
    },
    {
     "target": "aliasByNode(collectd.$Server.*.disk_ops.*, 2, 3, 4)"
    }
   ]
  },
  { "title": "Memory / Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "target": "alias(collectd.$Server.memory.memory-buffered, 'Buffered')"
    },
    {
     "target": "alias(collectd.$Server.memory.memory-cached, 'Cached')"
    },
    {
     "target": "alias(collectd.$Server.memory.memory-used, 'Used')"
    },
    {
     "target": "alias(collectd.$Server.memory.memory-slab_recl, 'Slab Recl')"
    },
    {
     "target": "alias(collectd.$Server.memory.memory-slab_unrecl, 'Slab Unrecl')"
    },
    {
     "target": "alias(collectd.$Server.memory.memory-free, 'Free')"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(scale(collectd.$Server.*.if_octets.rx, 8), 'RX')"
    },
    {
     "target": "alias(scale(collectd.$Server.*.if_octets.tx, 8), 'TX')"
    }
   ]
  }
 ]
}